import { BillingItem } from "@/pages/dashboard/admin/BillingAndPayment";

export const AllDoctorsData = [
  {
    ID: "D001",
    Name: "Dr. John Doe",
    image: "https://picsum.photos/200/120?random=1",
    Specialty: "Cardiology",
    Status: "Active",
  },
  {
    ID: "D002",
    Name: "Dr. Jane Smith",
    image: "https://picsum.photos/200/120?random=1",
    Specialty: "Neurology",
    Status: "Inactive",
  },
  {
    ID: "D003",
    Name: "Dr. Alice Johnson",
    image: "https://picsum.photos/200/120?random=1",
    Specialty: "Pediatrics",
    Status: "Active",
  },
  {
    ID: "D004",
    Name: "Dr. Bob Brown",
    image: "https://picsum.photos/200/120?random=1",
    Specialty: "Dermatology",
    Status: "Active",
  },
  {
    ID: "D005",
    Name: "Dr. Carol White",
    image: "https://picsum.photos/200/120?random=1",
    Specialty: "Oncology",
    Status: "Inactive",
  },
  {
    ID: "D006",
    Name: "Dr. David Green",
    image: "https://picsum.photos/200/120?random=1",
    Specialty: "Orthopedics",
    Status: "Active",
  },
  {
    ID: "D007",
    Name: "Dr. Eva Black",
    image: "https://picsum.photos/200/120?random=1",
    Specialty: "Gynecology",
    Status: "Active",
  },
  {
    ID: "D008",
    Name: "Dr. Frank Blue",
    image: "https://picsum.photos/200/120?random=1",
    Specialty: "Psychiatry",
    Status: "Inactive",
  },
  {
    ID: "D009",
    Name: "Dr. Grace Yellow",
    image: "https://picsum.photos/200/120?random=1",
    Specialty: "Radiology",
    Status: "Active",
  },
  {
    ID: "D010",
    Name: "Dr. Henry Purple",
    image: "https://picsum.photos/200/120?random=1",
    Specialty: "Urology",
    Status: "Active",
  },
  {
    ID: "D011",
    Name: "Dr. Irene Orange",
    image: "https://picsum.photos/200/120?random=1",
    Specialty: "Gastroenterology",
    Status: "Inactive",
  },
];

export const RecentlyApointed = [
  {
    ID: 1,
    Name: "Dr. John Doe",
    Gender: "F",
    Date: "12/08/2023",
    Time: "10:00 AM",
    AssignedPatient: "Mr. Smith",
    Status: "Confirmed",
  },
  {
    ID: 2,
    Name: "Dr. Jane Smith",
    Gender: "F",
    Date: "12/08/2023",
    Time: "10:00 AM",
    AssignedPatient: "Mr. Johnson",
    Status: "Confirmed",
  },
  {
    ID: 3,
    Name: "Dr. Alice Johnson",
    Gender: "F",
    Date: "12/08/2023",
    Time: "10:00 AM",
    AssignedPatient: "Mr. Brown",
    Status: "Pending",
  },
];

export const PatientsData = [
  {
    MRN: "MD/2025/001",
    Name: "Mr. John Doe",
    image: "https://picsum.photos/200/120?random=1",
    Gender: "F",
    Age: 45,
    Insurance: "Private",
    Status: "Active",
  },
  {
    MRN: "MD/2025/002",
    Name: "Ms. Jane Smith",
    image: "https://picsum.photos/200/120?random=2",
    Gender: "F",
    Age: 38,
    Insurance: "NHIS",
    Status: "Inactive",
  },
  {
    MRN: "MD/2025/003",
    Name: "Mr. Alice Johnson",
    image: "https://picsum.photos/200/120?random=3",
    Gender: "M",
    Age: 50,
    Insurance: "Private",
    Status: "Active",
  },
  {
    MRN: "MD/2025/003",
    Name: "Mr. Alice Johnson",
    image: "https://picsum.photos/200/120?random=3",
    Gender: "M",
    Age: 50,
    Insurance: "Private",
    Status: "Active",
  },
  {
    MRN: "MD/2025/003",
    Name: "Mr. Alice Johnson",
    image: "https://picsum.photos/200/120?random=3",
    Gender: "M",
    Age: 50,
    Insurance: "Private",
    Status: "Active",
  },
  {
    MRN: "MD/2025/003",
    Name: "Mr. Alice Johnson",
    image: "https://picsum.photos/200/120?random=3",
    Gender: "M",
    Age: 50,
    Insurance: "Private",
    Status: "Active",
  },
  {
    MRN: "MD/2025/003",
    Name: "Mr. Alice Johnson",
    image: "https://picsum.photos/200/120?random=3",
    Gender: "M",
    Age: 50,
    Insurance: "Private",
    Status: "Active",
  },
  {
    MRN: "MD/2025/003",
    Name: "Mr. Alice Johnson",
    image: "https://picsum.photos/200/120?random=3",
    Gender: "M",
    Age: 50,
    Insurance: "Private",
    Status: "Active",
  },
  {
    MRN: "MD/2025/003",
    Name: "Mr. Alice Johnson",
    image: "https://picsum.photos/200/120?random=3",
    Gender: "M",
    Age: 50,
    Insurance: "Private",
    Status: "Active",
  },
  {
    MRN: "MD/2025/003",
    Name: "Mr. Alice Johnson",
    image: "https://picsum.photos/200/120?random=3",
    Gender: "M",
    Age: 50,
    Insurance: "Private",
    Status: "Active",
  },
  {
    MRN: "MD/2025/003",
    Name: "Mr. Alice Johnson",
    image: "https://picsum.photos/200/120?random=3",
    Gender: "M",
    Age: 50,
    Insurance: "Private",
    Status: "Active",
  },
  {
    MRN: "MD/2025/003",
    Name: "Mr. Alice Johnson",
    image: "https://picsum.photos/200/120?random=3",
    Gender: "M",
    Age: 50,
    Insurance: "Private",
    Status: "Active",
  },
  {
    MRN: "MD/2025/003",
    Name: "Mr. Alice Johnson",
    image: "https://picsum.photos/200/120?random=3",
    Gender: "M",
    Age: 50,
    Insurance: "Private",
    Status: "Active",
  },
  {
    MRN: "MD/2025/003",
    Name: "Mr. Alice Johnson",
    image: "https://picsum.photos/200/120?random=3",
    Gender: "M",
    Age: 50,
    Insurance: "Private",
    Status: "Active",
  },
  {
    MRN: "MD/2025/003",
    Name: "Mr. Alice Johnson",
    image: "https://picsum.photos/200/120?random=3",
    Gender: "M",
    Age: 50,
    Insurance: "Private",
    Status: "Active",
  },
];

export const PlatformData = [
  {
    id: crypto.randomUUID(),
    Name: "John Doe",
    Image: "https://picsum.photos/200/120?random=1",
    Date: "20-08-2023",
    Event: "User Login",
    Role: "patient",
  },
  {
    id: crypto.randomUUID(),
    Name: "Sam Jason",
    Image: "https://picsum.photos/200/120?random=1",
    Date: "20-08-2023",
    Event: "Appointment Booked",
    Role: "doctor",
  },
  {
    id: crypto.randomUUID(),
    Name: "Grace Billy",
    Image: "https://picsum.photos/200/120?random=1",
    Date: "20-08-2023",
    Event: "Payment made",
    Role: "nurse",
  },
];

export const staffData = [
  {
    id: crypto.randomUUID(),
    name: "John Doe",
    role: "Admin",
    image: "https://picsum.photos/200/120?random=1",
    suspension: false,
    assigned: true,
  },
  {
    id: crypto.randomUUID(),
    name: "Dr. Emily Carter",
    role: "Doctor",
    image: "https://picsum.photos/200/120?random=2",
    suspension: false,
    assigned: true,
  },
  {
    id: crypto.randomUUID(),
    name: "Mrs. Duke James",
    role: "Admin",
    image: "https://picsum.photos/200/120?random=3",
    suspension: false,
    assigned: true,
  },
  {
    id: crypto.randomUUID(),
    name: "Miss. Carter",
    role: "Receptionist",
    image: "https://picsum.photos/200/120?random=4",
    suspension: false,
    assigned: true,
  },
  {
    id: crypto.randomUUID(),
    name: "Dr. Carter John",
    role: "Secretary",
    image: "https://picsum.photos/200/120?random=5",
    suspension: false,
    assigned: true,
  },
  {
    id: crypto.randomUUID(),
    name: "Dr. Sarah Johnson",
    role: "Nurse",
    image: "https://picsum.photos/200/120?random=6",
    suspension: true,
    assigned: false,
  },
  {
    id: crypto.randomUUID(),
    name: "Dr. David Brown",
    role: "Pharmacist",
    image: "https://picsum.photos/200/120?random=7",
    suspension: false,
    assigned: true,
  },
  {
    id: crypto.randomUUID(),
    name: "Dr. Olivia White",
    role: "Lab Technician",
    image: "https://picsum.photos/200/120?random=8",
    suspension: true,
    assigned: false,
  },
  {
    id: crypto.randomUUID(),
    name: "Dr. James Green",
    role: "Doctor",
    image: "https://picsum.photos/200/120?random=9",
    suspension: false,
    assigned: true,
  },
  {
    id: crypto.randomUUID(),
    name: "Nurse Kate Miller",
    role: "Nurse",
    image: "https://picsum.photos/200/120?random=10",
    suspension: false,
    assigned: true,
  },
  {
    id: crypto.randomUUID(),
    name: "Dr. Ethan Wilson",
    role: "Secretary",
    image: "https://picsum.photos/200/120?random=11",
    suspension: true,
    assigned: false,
  },
  {
    id: crypto.randomUUID(),
    name: "Dr. Michael Adams",
    role: "Doctor",
    image: "https://picsum.photos/200/120?random=12",
    suspension: false,
    assigned: true,
  },
  {
    id: crypto.randomUUID(),
    name: "Dr. Amanda Roberts",
    role: "Receptionist",
    image: "https://picsum.photos/200/120?random=13",
    suspension: false,
    assigned: true,
  },
];

export const ReportData = [
  {
    reportId: crypto.randomUUID(),
    Date: "20-08-2023",
    Time: "2:00pm",
    ActivityType: "Payment",
    DescriptionDetails: "Patient A made a payment of ₦5,000 for drugs",
    status: "successful",
  },
  {
    reportId: crypto.randomUUID(),
    Date: "20-03-2023",
    Time: "12:00pm",
    ActivityType: "User Login",
    DescriptionDetails: "Nurse Abi logged into the dashboard",
    status: "pending",
  },
  {
    reportId: crypto.randomUUID(),
    Date: "05-04-2023",
    Time: "9:30am",
    ActivityType: "User Logout",
    DescriptionDetails: "Dr. James Green logged out of the system",
    status: "successful",
  },
  {
    reportId: crypto.randomUUID(),
    Date: "17-05-2023",
    Time: "11:45am",
    ActivityType: "Record Update",
    DescriptionDetails: "Receptionist updated patient B's contact information",
    status: "successful",
  },
  {
    reportId: crypto.randomUUID(),
    Date: "30-06-2023",
    Time: "4:15pm",
    ActivityType: "Payment",
    DescriptionDetails: "Patient C made a payment of ₦12,000 for consultation",
    status: "failed",
  },
  {
    reportId: crypto.randomUUID(),
    Date: "12-07-2023",
    Time: "3:05pm",
    ActivityType: "Appointment Scheduling",
    DescriptionDetails:
      "Dr. Emily Carter scheduled a follow-up appointment with Patient D",
    status: "successful",
  },
  {
    reportId: crypto.randomUUID(),
    Date: "28-07-2023",
    Time: "10:20am",
    ActivityType: "User Login",
    DescriptionDetails: "Admin John Doe logged into the dashboard",
    status: "successful",
  },
  {
    reportId: crypto.randomUUID(),
    Date: "08-08-2023",
    Time: "1:40pm",
    ActivityType: "Record Deletion",
    DescriptionDetails:
      "Secretary removed inactive patient record from the database",
    status: "failed",
  },
  {
    reportId: crypto.randomUUID(),
    Date: "10-08-2023",
    Time: "5:10pm",
    ActivityType: "Inventory Update",
    DescriptionDetails:
      "Pharmacist updated stock quantity for Amoxicillin (250mg)",
    status: "successful",
  },
  {
    reportId: crypto.randomUUID(),
    Date: "15-08-2023",
    Time: "9:00am",
    ActivityType: "User Logout",
    DescriptionDetails: "Nurse Kate Miller logged out of the dashboard",
    status: "successful",
  },
  {
    reportId: crypto.randomUUID(),
    Date: "18-08-2023",
    Time: "8:45am",
    ActivityType: "Login Attempt",
    DescriptionDetails: "Failed login attempt detected for user 'guest'",
    status: "failed",
  },
  {
    reportId: crypto.randomUUID(),
    Date: "22-08-2023",
    Time: "2:20pm",
    ActivityType: "Prescription Upload",
    DescriptionDetails:
      "Dr. David Brown uploaded a new prescription for Patient E",
    status: "successful",
  },
  {
    reportId: crypto.randomUUID(),
    Date: "25-08-2023",
    Time: "6:30pm",
    ActivityType: "Billing Update",
    DescriptionDetails: "Finance Officer adjusted bill for Patient F (₦8,500)",
    status: "pending",
  },
];

// Mock data - replace with your actual data source
export const notificationsData = [
  {
    id: 1,
    patientName: "Mr John Doe",
    message: "Patients requested for special treatment from you",
    date: "12-02-2025",
    time: "19:30",
    type: "treatment_request",
    status: "unread",
    category: "today",
    email: "john.doe@example.com",
    phone: "+1234567890",
  },
  {
    id: 2,
    patientName: "Ms Sarah Smith",
    message: "Appointment confirmation for next week",
    date: "11-02-2025",
    time: "14:15",
    type: "appointment",
    status: "read",
    category: "week",
    email: "sarah.smith@example.com",
    phone: "+1234567891",
  },
  {
    id: 3,
    patientName: "Dr Michael Brown",
    message: "New test results available for review",
    date: "10-02-2025",
    time: "09:45",
    type: "test_results",
    status: "unread",
    category: "month",
    email: "michael.brown@example.com",
    phone: "+1234567892",
  },
  // Add more mock data as needed...
];

export // Mock billing data - replace with your actual data
const billingData: BillingItem[] = [
  {
    id: "1",
    invoiceNo: "#INV12334",
    date: "Sept 9, 2025",
    description: "Consultation",
    amount: 20000,
    status: "paid",
    patientName: "John Doe",
    serviceType: "Consultation",
  },
  {
    id: "2",
    invoiceNo: "#INV12335",
    date: "Sept 8, 2025",
    description: "Laboratory Tests",
    amount: 15000,
    status: "pending",
    patientName: "Sarah Smith",
    serviceType: "Laboratory",
  },
  {
    id: "3",
    invoiceNo: "#INV12336",
    date: "Sept 7, 2025",
    description: "X-Ray Scan",
    amount: 25000,
    status: "overdue",
    patientName: "Michael Brown",
    serviceType: "Radiology",
  },
  {
    id: "4",
    invoiceNo: "#INV12337",
    date: "Sept 6, 2025",
    description: "Dental Checkup",
    amount: 12000,
    status: "paid",
    patientName: "Emily Johnson",
    serviceType: "Dental",
  },
  {
    id: "5",
    invoiceNo: "#INV12338",
    date: "Sept 5, 2025",
    description: "Physiotherapy",
    amount: 18000,
    status: "pending",
    patientName: "David Wilson",
    serviceType: "Physiotherapy",
  },
  // Add more data as needed...
];
